import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

async function main() {
  console.log("Seeding database...");

  // Clear existing data
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();

  // Create categories
  const categories = await Promise.all([
    prisma.category.create({
      data: {
        name: "Bearings & Bushings",
        slug: "bearings-bushings",
        icon: "🔩",
      },
    }),
    prisma.category.create({
      data: {
        name: "Fasteners & Hardware",
        slug: "fasteners-hardware",
        icon: "🔧",
      },
    }),
    prisma.category.create({
      data: {
        name: "Electrical & Controls",
        slug: "electrical-controls",
        icon: "⚡",
      },
    }),
    prisma.category.create({
      data: {
        name: "Hand & Power Tools",
        slug: "hand-power-tools",
        icon: "🛠️",
      },
    }),
    prisma.category.create({
      data: {
        name: "Hydraulics & Pneumatics",
        slug: "hydraulics-pneumatics",
        icon: "💧",
      },
    }),
    prisma.category.create({
      data: {
        name: "Belts, Chains & Gears",
        slug: "belts-chains-gears",
        icon: "⚙️",
      },
    }),
    prisma.category.create({
      data: {
        name: "Safety & PPE",
        slug: "safety-ppe",
        icon: "🦺",
      },
    }),
    prisma.category.create({
      data: {
        name: "Motors & Pumps",
        slug: "motors-pumps",
        icon: "🏭",
      },
    }),
  ]);

  const [
    bearings,
    fasteners,
    electrical,
    tools,
    hydraulics,
    belts,
    safety,
    motors,
  ] = categories;

  console.log(`Created ${categories.length} categories.`);

  // Products for Bearings & Bushings
  const bearingProducts = [
    {
      name: "SKF Deep Groove Ball Bearing 6205-2RS",
      brand: "SKF",
      sku: "SKF-6205-2RS",
      mrp: 850,
      sellingPrice: 680,
      description:
        "SKF 6205-2RS deep groove ball bearing with rubber seals on both sides. Ideal for electric motors, gearboxes, and pumps. Pre-greased and maintenance-free.",
      specifications: JSON.stringify({
        "Inner Diameter": "25 mm",
        "Outer Diameter": "52 mm",
        Width: "15 mm",
        "Dynamic Load Rating": "14.8 kN",
        "Static Load Rating": "7.8 kN",
        "Max Speed": "13000 rpm",
        Sealing: "Rubber seals both sides",
        Material: "Chrome steel",
      }),
      categoryId: bearings.id,
      slug: "skf-deep-groove-ball-bearing-6205-2rs",
      inStock: true,
    },
    {
      name: "SKF Cylindrical Roller Bearing NU 205 ECP",
      brand: "SKF",
      sku: "SKF-NU205-ECP",
      mrp: 1450,
      sellingPrice: 1160,
      description:
        "SKF NU 205 ECP single row cylindrical roller bearing. Suitable for heavy radial loads in gearboxes, paper machines, and rolling mills.",
      specifications: JSON.stringify({
        "Inner Diameter": "25 mm",
        "Outer Diameter": "52 mm",
        Width: "15 mm",
        "Dynamic Load Rating": "28.5 kN",
        "Static Load Rating": "18.5 kN",
        "Max Speed": "12000 rpm",
        Type: "Cylindrical Roller",
        Series: "NU 200",
      }),
      categoryId: bearings.id,
      slug: "skf-cylindrical-roller-bearing-nu-205-ecp",
      inStock: true,
    },
    {
      name: "FAG Tapered Roller Bearing 30205",
      brand: "FAG",
      sku: "FAG-30205",
      mrp: 1200,
      sellingPrice: 960,
      description:
        "FAG 30205 tapered roller bearing for combined radial and axial loads. Used in automotive differentials, gearboxes, and construction equipment.",
      specifications: JSON.stringify({
        "Inner Diameter": "25 mm",
        "Outer Diameter": "52 mm",
        Width: "16.25 mm",
        "Dynamic Load Rating": "29 kN",
        "Static Load Rating": "22.4 kN",
        Angle: "14.83°",
        Type: "Tapered Roller",
        Standard: "ISO 355",
      }),
      categoryId: bearings.id,
      slug: "fag-tapered-roller-bearing-30205",
      inStock: true,
    },
    {
      name: "NTN Self-Aligning Ball Bearing 1205K",
      brand: "NTN",
      sku: "NTN-1205K",
      mrp: 980,
      sellingPrice: 784,
      description:
        "NTN 1205K self-aligning ball bearing with tapered bore. Accommodates shaft misalignment up to 3°. Suitable for conveyors and agricultural machinery.",
      specifications: JSON.stringify({
        "Inner Diameter": "25 mm",
        "Outer Diameter": "52 mm",
        Width: "15 mm",
        "Dynamic Load Rating": "11.4 kN",
        "Static Load Rating": "4.0 kN",
        "Max Misalignment": "3°",
        Type: "Self-Aligning Ball",
        Bore: "Tapered 1:12",
      }),
      categoryId: bearings.id,
      slug: "ntn-self-aligning-ball-bearing-1205k",
      inStock: true,
    },
    {
      name: "SKF Spherical Roller Bearing 22205 E",
      brand: "SKF",
      sku: "SKF-22205-E",
      mrp: 2800,
      sellingPrice: 2240,
      description:
        "SKF 22205 E spherical roller bearing for heavy-duty applications with high radial and axial loads. Used in crushers, conveyors, and heavy machinery.",
      specifications: JSON.stringify({
        "Inner Diameter": "25 mm",
        "Outer Diameter": "52 mm",
        Width: "18 mm",
        "Dynamic Load Rating": "43 kN",
        "Static Load Rating": "34 kN",
        "Max Misalignment": "2.5°",
        Type: "Spherical Roller",
        Cage: "Steel",
      }),
      categoryId: bearings.id,
      slug: "skf-spherical-roller-bearing-22205-e",
      inStock: true,
    },
    {
      name: "Bronze Flanged Bushing 30x35x30mm",
      brand: "Oilite",
      sku: "OIL-FB-303530",
      mrp: 420,
      sellingPrice: 336,
      description:
        "Oil-impregnated sintered bronze flanged bushing. Self-lubricating, maintenance-free. Ideal for slow-speed and oscillating motion applications.",
      specifications: JSON.stringify({
        "Inner Diameter": "30 mm",
        "Outer Diameter": "35 mm",
        Length: "30 mm",
        Material: "Sintered Bronze (CuSn10)",
        "Max Load": "60 MPa",
        "Max Speed": "0.5 m/s",
        Lubrication: "Self-lubricating",
        Standard: "ISO 2795",
      }),
      categoryId: bearings.id,
      slug: "bronze-flanged-bushing-30x35x30mm",
      inStock: true,
    },
    {
      name: "SKF Angular Contact Ball Bearing 7205 BECBP",
      brand: "SKF",
      sku: "SKF-7205-BECBP",
      mrp: 1650,
      sellingPrice: 1320,
      description:
        "SKF 7205 BECBP single row angular contact ball bearing. 40° contact angle for combined axial and radial loads. Used in spindles and machine tools.",
      specifications: JSON.stringify({
        "Inner Diameter": "25 mm",
        "Outer Diameter": "52 mm",
        Width: "15 mm",
        "Contact Angle": "40°",
        "Dynamic Load Rating": "15.9 kN",
        "Static Load Rating": "9.5 kN",
        "Max Speed": "14000 rpm",
        Type: "Angular Contact Ball",
      }),
      categoryId: bearings.id,
      slug: "skf-angular-contact-ball-bearing-7205-becbp",
      inStock: true,
    },
  ];

  // Products for Fasteners & Hardware
  const fastenerProducts = [
    {
      name: "Hex Bolt M12x50 Grade 8.8 Zinc Plated (Pack of 50)",
      brand: "Unbrako",
      sku: "UNB-HB-M12X50-G88",
      mrp: 680,
      sellingPrice: 544,
      description:
        "Unbrako M12x50 hexagon head bolt, Grade 8.8, zinc plated for corrosion resistance. Suitable for structural and mechanical assemblies.",
      specifications: JSON.stringify({
        Size: "M12 x 50 mm",
        Grade: "8.8",
        Finish: "Zinc Plated",
        "Head Type": "Hexagon",
        Thread: "Metric Coarse (1.75 mm pitch)",
        Material: "Alloy Steel",
        Standard: "IS 1364 / DIN 931",
        "Pack Qty": "50 pieces",
      }),
      categoryId: fasteners.id,
      slug: "hex-bolt-m12x50-grade-88-zinc-plated-pack-of-50",
      inStock: true,
    },
    {
      name: "Stainless Steel Hex Nut M10 SS316 (Pack of 100)",
      brand: "Mahavir",
      sku: "MAH-HN-M10-SS316",
      mrp: 580,
      sellingPrice: 464,
      description:
        "M10 hexagon nut in SS316 stainless steel. Excellent corrosion resistance for marine and chemical plant environments.",
      specifications: JSON.stringify({
        Size: "M10",
        Grade: "SS316",
        "Width Across Flats": "17 mm",
        Height: "8 mm",
        Thread: "Metric Coarse (1.5 mm pitch)",
        Material: "Stainless Steel 316",
        Standard: "DIN 934 / IS 1364",
        "Pack Qty": "100 pieces",
      }),
      categoryId: fasteners.id,
      slug: "stainless-steel-hex-nut-m10-ss316-pack-of-100",
      inStock: true,
    },
    {
      name: "Allen Cap Screw M8x25 Grade 12.9 Black (Pack of 100)",
      brand: "Unbrako",
      sku: "UNB-ACS-M8X25-G129",
      mrp: 750,
      sellingPrice: 600,
      description:
        "Unbrako M8x25 socket head cap screw, Grade 12.9, black oxide finish. High tensile strength for precision engineering applications.",
      specifications: JSON.stringify({
        Size: "M8 x 25 mm",
        Grade: "12.9",
        Finish: "Black Oxide",
        "Head Type": "Socket Head",
        "Socket Size": "6 mm Hex",
        Material: "Alloy Steel",
        Standard: "DIN 912 / IS 2269",
        "Pack Qty": "100 pieces",
      }),
      categoryId: fasteners.id,
      slug: "allen-cap-screw-m8x25-grade-129-black-pack-of-100",
      inStock: true,
    },
    {
      name: "Spring Washer M12 Zinc Plated (Pack of 200)",
      brand: "Sundram",
      sku: "SUN-SW-M12-ZP",
      mrp: 280,
      sellingPrice: 224,
      description:
        "M12 split spring lock washers, zinc plated. Prevents bolt loosening due to vibration. Widely used in machinery and structural assemblies.",
      specifications: JSON.stringify({
        Size: "M12",
        "Inner Diameter": "12.2 mm",
        "Outer Diameter": "22.5 mm",
        Thickness: "3.1 mm",
        Finish: "Zinc Plated",
        Material: "Spring Steel (65Mn)",
        Standard: "DIN 127B / IS 3063",
        "Pack Qty": "200 pieces",
      }),
      categoryId: fasteners.id,
      slug: "spring-washer-m12-zinc-plated-pack-of-200",
      inStock: true,
    },
    {
      name: "Stud Bolt M16x100 with 2 Nuts Grade B7",
      brand: "Bharat Bolts",
      sku: "BB-SB-M16X100-B7",
      mrp: 320,
      sellingPrice: 256,
      description:
        "M16x100 stud bolt with 2 hex nuts, ASTM A193 Grade B7. Used for high-temperature and high-pressure flange connections in pipelines and vessels.",
      specifications: JSON.stringify({
        Size: "M16 x 100 mm",
        Grade: "ASTM A193 B7",
        "Nut Grade": "ASTM A194 2H",
        Thread: "Metric Coarse (2.0 mm pitch)",
        "Tensile Strength": "125 ksi (862 MPa)",
        Material: "Alloy Steel Cr-Mo",
        "Temp Range": "-50°C to +450°C",
        Finish: "Plain / Black",
      }),
      categoryId: fasteners.id,
      slug: "stud-bolt-m16x100-with-2-nuts-grade-b7",
      inStock: true,
    },
    {
      name: "Self-Drilling Screw 4.2x13mm Zinc (Pack of 500)",
      brand: "Rawlplug",
      sku: "RAW-SDS-4213-ZP",
      mrp: 420,
      sellingPrice: 336,
      description:
        "Zinc-plated self-drilling screws for sheet metal and thin steel sections. No pre-drilling required. Pan head with Phillips drive.",
      specifications: JSON.stringify({
        Size: "4.2 x 13 mm",
        Head: "Pan Head",
        Drive: "Phillips #2",
        "Drill Capacity": "0.8 mm to 4 mm steel",
        Finish: "Zinc Plated",
        Material: "Carbon Steel",
        Standard: "DIN 7504K",
        "Pack Qty": "500 pieces",
      }),
      categoryId: fasteners.id,
      slug: "self-drilling-screw-42x13mm-zinc-pack-of-500",
      inStock: true,
    },
    {
      name: "Anchor Bolt M10x100 with Nut & Washer (Pack of 25)",
      brand: "Fischer",
      sku: "FIS-AB-M10X100",
      mrp: 890,
      sellingPrice: 712,
      description:
        "Fischer M10x100 mechanical expansion anchor bolt complete with nut and washer. For concrete and masonry fixing of machinery and structures.",
      specifications: JSON.stringify({
        Size: "M10 x 100 mm",
        "Setting Depth": "50 mm",
        "Drill Hole": "10 mm",
        "Approved Load": "5.5 kN (Tension)",
        "Approved Load Shear": "8.2 kN",
        Material: "Electro-galvanized Steel",
        Standard: "ETA approved",
        "Pack Qty": "25 pieces",
      }),
      categoryId: fasteners.id,
      slug: "anchor-bolt-m10x100-with-nut-washer-pack-of-25",
      inStock: true,
    },
  ];

  // Products for Electrical & Controls
  const electricalProducts = [
    {
      name: "Havells 25A Double Pole MCB C-Curve",
      brand: "Havells",
      sku: "HAV-MCB-DP-25A-C",
      mrp: 850,
      sellingPrice: 680,
      description:
        "Havells 25A 2-pole miniature circuit breaker with C-curve tripping characteristic. For protection of industrial loads and distribution boards.",
      specifications: JSON.stringify({
        "Current Rating": "25 A",
        Poles: "2 (Double Pole)",
        "Tripping Curve": "C",
        "Breaking Capacity": "10 kA",
        Voltage: "240/415V AC",
        Frequency: "50/60 Hz",
        Standard: "IS 8828 / IEC 60898",
        Mounting: "DIN Rail 35mm",
      }),
      categoryId: electrical.id,
      slug: "havells-25a-double-pole-mcb-c-curve",
      inStock: true,
    },
    {
      name: "Schneider Electric Contactor LC1D25 25A 3P 230V",
      brand: "Schneider",
      sku: "SCH-LC1D25-230V",
      mrp: 2200,
      sellingPrice: 1760,
      description:
        "Schneider Electric TeSys D series 25A 3-pole AC contactor with 230V AC coil. For motor control and power switching in industrial applications.",
      specifications: JSON.stringify({
        "Current Rating": "25 A AC-3",
        Poles: "3",
        "Coil Voltage": "230V AC 50/60 Hz",
        "Motor Rating": "11 kW / 400V",
        "Auxiliary Contacts": "1 NO + 1 NC",
        "Breaking Capacity": "AC-3",
        Standard: "IEC 60947-4-1",
        Mounting: "DIN Rail / Screw",
      }),
      categoryId: electrical.id,
      slug: "schneider-electric-contactor-lc1d25-25a-3p-230v",
      inStock: true,
    },
    {
      name: "Polycab 2.5 Sq mm FR PVC Wire 90m Roll Red",
      brand: "Polycab",
      sku: "POL-FR-25-90M-R",
      mrp: 1850,
      sellingPrice: 1480,
      description:
        "Polycab 2.5 sq mm single core FR-PVC insulated copper wire, 90m roll, red. Ideal for house wiring, panels, and industrial installations.",
      specifications: JSON.stringify({
        "Cross Section": "2.5 sq mm",
        Conductor: "Multi-strand Annealed Copper",
        Insulation: "FR-PVC",
        Color: "Red",
        "Current Capacity": "24 A",
        "Voltage Rating": "1100V",
        Standard: "IS 694",
        "Roll Length": "90 m",
      }),
      categoryId: electrical.id,
      slug: "polycab-25-sq-mm-fr-pvc-wire-90m-roll-red",
      inStock: true,
    },
    {
      name: "L&T 40A RCCB 4 Pole 30mA Sensitivity",
      brand: "L&T",
      sku: "LT-RCCB-40A-4P-30mA",
      mrp: 3200,
      sellingPrice: 2560,
      description:
        "L&T 40A 4-pole residual current circuit breaker with 30mA sensitivity. Provides protection against earth leakage and electric shock.",
      specifications: JSON.stringify({
        "Current Rating": "40 A",
        Poles: "4",
        Sensitivity: "30 mA",
        "Breaking Capacity": "10 kA",
        Voltage: "415V AC",
        "Trip Time": "< 30 ms",
        Standard: "IS 12640 / IEC 61008",
        Type: "AC type",
      }),
      categoryId: electrical.id,
      slug: "lt-40a-rccb-4-pole-30ma-sensitivity",
      inStock: true,
    },
    {
      name: "Omron MY4N-J 14-Pin General Purpose Relay 24VDC",
      brand: "Omron",
      sku: "OMR-MY4NJ-24VDC",
      mrp: 680,
      sellingPrice: 544,
      description:
        "Omron MY4N-J 4PDT general purpose relay with 14-pin plug-in socket. 24VDC coil, 5A contact rating. Used in control panels and automation.",
      specifications: JSON.stringify({
        "Coil Voltage": "24V DC",
        "Contact Configuration": "4PDT (4 poles)",
        "Contact Rating": "5A / 250V AC",
        "Operate Time": "< 20 ms",
        "Release Time": "< 20 ms",
        "Insulation Resistance": "1000 MΩ min",
        Terminal: "14-pin plug-in",
        Standard: "UL / CE approved",
      }),
      categoryId: electrical.id,
      slug: "omron-my4n-j-14-pin-general-purpose-relay-24vdc",
      inStock: true,
    },
    {
      name: "Havells 16A Industrial Socket 3P+N+E IP44",
      brand: "Havells",
      sku: "HAV-IND-SKT-16A-5P",
      mrp: 1100,
      sellingPrice: 880,
      description:
        "Havells 16A industrial socket outlet, 5-pin (3P+N+E), IP44 rated for splash-proof protection. For industrial machinery and equipment connections.",
      specifications: JSON.stringify({
        "Current Rating": "16 A",
        Pins: "5 (3P+N+E)",
        "IP Rating": "IP44",
        Voltage: "380-415V AC",
        Color: "Red",
        Material: "Polycarbonate",
        Mounting: "Panel mount",
        Standard: "IEC 60309",
      }),
      categoryId: electrical.id,
      slug: "havells-16a-industrial-socket-3pne-ip44",
      inStock: true,
    },
    {
      name: "Siemens LOGO! 8 Programmable Logic Controller 24V",
      brand: "Siemens",
      sku: "SIE-LOGO-8-24V",
      mrp: 8500,
      sellingPrice: 6800,
      description:
        "Siemens LOGO! 8 compact programmable logic controller with 24V DC supply. 8 digital inputs, 4 digital outputs. Built-in display and Ethernet port.",
      specifications: JSON.stringify({
        "Supply Voltage": "24V DC",
        "Digital Inputs": "8",
        "Digital Outputs": "4 (Relay)",
        "Analog Inputs": "4 (0-10V)",
        Display: "Built-in LCD",
        Communication: "Ethernet",
        Memory: "400 blocks",
        Standard: "CE / UL / cULus",
      }),
      categoryId: electrical.id,
      slug: "siemens-logo-8-programmable-logic-controller-24v",
      inStock: true,
    },
  ];

  // Products for Hand & Power Tools
  const toolProducts = [
    {
      name: "Taparia 19mm Combination Spanner Chrome Vanadium",
      brand: "Taparia",
      sku: "TAP-CS-19",
      mrp: 280,
      sellingPrice: 224,
      description:
        "Taparia 19mm combination spanner (open + ring end) made from chrome vanadium steel. Drop forged, heat treated, and mirror polished.",
      specifications: JSON.stringify({
        Size: "19 mm",
        Type: "Combination (Open + Ring)",
        Material: "Chrome Vanadium Steel",
        Finish: "Mirror Polish / Chrome Plated",
        "Ring End": "12-point",
        Standard: "IS 2028",
        "Torque Capacity": "180 Nm",
        Made: "India",
      }),
      categoryId: tools.id,
      slug: "taparia-19mm-combination-spanner-chrome-vanadium",
      inStock: true,
    },
    {
      name: "Bosch GSB 550 Professional Impact Drill 550W",
      brand: "Bosch",
      sku: "BOS-GSB-550",
      mrp: 3200,
      sellingPrice: 2560,
      description:
        "Bosch GSB 550 professional impact drill with 550W motor. Variable speed, forward/reverse, and hammer function. Ideal for drilling in concrete, masonry, wood, and metal.",
      specifications: JSON.stringify({
        Power: "550 W",
        "No Load Speed": "0-3000 rpm",
        "Max Torque": "13 Nm",
        "Chuck Size": "13 mm keyless",
        "Drilling Capacity (Concrete)": "13 mm",
        "Drilling Capacity (Steel)": "10 mm",
        "Drilling Capacity (Wood)": "25 mm",
        Weight: "1.9 kg",
      }),
      categoryId: tools.id,
      slug: "bosch-gsb-550-professional-impact-drill-550w",
      inStock: true,
    },
    {
      name: "Stanley 30-Piece Socket Set 3/8\" Drive Metric",
      brand: "Stanley",
      sku: "STA-SOCK-30PC-38M",
      mrp: 2800,
      sellingPrice: 2240,
      description:
        "Stanley 30-piece 3/8\" drive socket set with metric sockets (8mm to 24mm), ratchet handle, extensions, and blow mold case. Chrome vanadium steel.",
      specifications: JSON.stringify({
        "Drive Size": '3/8"',
        "Socket Range": "8 mm - 24 mm",
        "Total Pieces": "30",
        "Ratchet": "72-tooth quick release",
        Extensions: '3" + 6"',
        Material: "Chrome Vanadium Steel",
        Finish: "Chrome Plated",
        Case: "Blow mold case included",
      }),
      categoryId: tools.id,
      slug: "stanley-30-piece-socket-set-38-drive-metric",
      inStock: true,
    },
    {
      name: "Bosch GWS 750 Professional Angle Grinder 4\" 750W",
      brand: "Bosch",
      sku: "BOS-GWS-750-4IN",
      mrp: 2850,
      sellingPrice: 2280,
      description:
        "Bosch GWS 750 4-inch angle grinder with 750W motor. Lightweight and compact for grinding, cutting, and polishing applications.",
      specifications: JSON.stringify({
        Power: "750 W",
        "No Load Speed": "11000 rpm",
        "Disc Diameter": "100 mm (4\")",
        "Spindle Thread": "M10",
        "Guard": "Adjustable protective guard",
        Weight: "1.7 kg",
        "Cable Length": "3 m",
        Standard: "IS 12773",
      }),
      categoryId: tools.id,
      slug: "bosch-gws-750-professional-angle-grinder-4-750w",
      inStock: true,
    },
    {
      name: "Taparia Adjustable Wrench 12\" Chrome Vanadium",
      brand: "Taparia",
      sku: "TAP-AW-12",
      mrp: 650,
      sellingPrice: 520,
      description:
        "Taparia 12-inch adjustable spanner with worm gear adjustment mechanism. Chrome vanadium steel construction with ergonomic grip handle.",
      specifications: JSON.stringify({
        Length: '12" (300 mm)',
        "Jaw Opening": "34 mm max",
        Material: "Chrome Vanadium Steel",
        Finish: "Satin Chrome",
        "Adjustment": "Worm gear",
        Standard: "IS 6994",
        Weight: "560 g",
        Made: "India",
      }),
      categoryId: tools.id,
      slug: "taparia-adjustable-wrench-12-chrome-vanadium",
      inStock: true,
    },
    {
      name: "Stanley FATMAX Hacksaw Frame with Blade 300mm",
      brand: "Stanley",
      sku: "STA-FM-HACK-300",
      mrp: 480,
      sellingPrice: 384,
      description:
        "Stanley FATMAX professional hacksaw with heavy-duty aluminum frame and bi-metal blade. Adjustable tension for maximum blade life and straight cuts.",
      specifications: JSON.stringify({
        "Blade Length": "300 mm (12\")",
        "Frame Material": "Heavy-duty Aluminum",
        "Blade Material": "Bi-metal (HCS + HSS)",
        TPI: "24 TPI",
        "Tension": "Adjustable",
        "Blade Angle": "0° / 45° / 90°",
        Weight: "480 g",
        "Blade Included": "Yes",
      }),
      categoryId: tools.id,
      slug: "stanley-fatmax-hacksaw-frame-with-blade-300mm",
      inStock: true,
    },
    {
      name: "Taparia 6-Piece Screwdriver Set Insulated 1000V",
      brand: "Taparia",
      sku: "TAP-SD-6PC-INS",
      mrp: 520,
      sellingPrice: 416,
      description:
        "Taparia 6-piece insulated screwdriver set rated for 1000V. Includes Phillips and flathead types. VDE approved for electrical work.",
      specifications: JSON.stringify({
        Pieces: "6",
        Types: "3x Phillips + 3x Slotted",
        "Voltage Rating": "1000V AC",
        Insulation: "Two-component handle",
        Material: "Chrome Vanadium Steel",
        Standard: "VDE / IEC 60900",
        Handle: "Ergonomic non-slip",
        Made: "India",
      }),
      categoryId: tools.id,
      slug: "taparia-6-piece-screwdriver-set-insulated-1000v",
      inStock: true,
    },
  ];

  // Products for Hydraulics & Pneumatics
  const hydraulicProducts = [
    {
      name: "Parker 1/2\" BSP Double Acting Hydraulic Cylinder 100mm Stroke",
      brand: "Parker",
      sku: "PAR-HAC-12BSP-100",
      mrp: 4800,
      sellingPrice: 3840,
      description:
        "Parker double-acting hydraulic cylinder, 1/2\" BSP ports, 50mm bore, 100mm stroke. Suitable for industrial presses, lifts, and clamping fixtures.",
      specifications: JSON.stringify({
        "Bore Diameter": "50 mm",
        "Rod Diameter": "28 mm",
        "Stroke Length": "100 mm",
        "Port Size": '1/2" BSP',
        "Max Pressure": "250 bar",
        "Max Force (extend)": "49 kN",
        Seals: "NBR (Nitrile)",
        "Temp Range": "-20°C to +80°C",
      }),
      categoryId: hydraulics.id,
      slug: "parker-12-bsp-double-acting-hydraulic-cylinder-100mm-stroke",
      inStock: true,
    },
    {
      name: "Festo DSNU-25-100-PPV Pneumatic Cylinder ISO 6432",
      brand: "Festo",
      sku: "FES-DSNU-25-100-PPV",
      mrp: 3200,
      sellingPrice: 2560,
      description:
        "Festo DSNU-25-100-PPV round cylinder, double acting, 25mm bore, 100mm stroke. ISO 6432 standard. Adjustable cushioning at both ends.",
      specifications: JSON.stringify({
        "Bore Diameter": "25 mm",
        "Stroke Length": "100 mm",
        "Working Pressure": "1-10 bar",
        "Max Force (6 bar)": "295 N",
        "Port Size": "M5",
        "Cushioning": "Adjustable both ends",
        Standard: "ISO 6432",
        "Temp Range": "-20°C to +80°C",
      }),
      categoryId: hydraulics.id,
      slug: "festo-dsnu-25-100-ppv-pneumatic-cylinder-iso-6432",
      inStock: true,
    },
    {
      name: "Bosch Rexroth Hydraulic Solenoid Valve 4/2-Way 24VDC",
      brand: "Bosch Rexroth",
      sku: "REX-4WE6-E-24VDC",
      mrp: 6500,
      sellingPrice: 5200,
      description:
        "Bosch Rexroth 4WE6E directional control valve, 4/2-way solenoid operated, 24V DC, NG6 cetop 3. For hydraulic circuit direction control.",
      specifications: JSON.stringify({
        "Valve Type": "4/2-way directional",
        "Coil Voltage": "24V DC",
        Size: "NG6 (Cetop 3)",
        "Max Flow": "60 L/min",
        "Max Pressure": "315 bar",
        "Switching Time": "< 50 ms",
        "Fluid Viscosity": "15-380 mm²/s",
        Seals: "FKM (Viton)",
      }),
      categoryId: hydraulics.id,
      slug: "bosch-rexroth-hydraulic-solenoid-valve-42-way-24vdc",
      inStock: true,
    },
    {
      name: "SMC AR20-N02B-Z Pneumatic Pressure Regulator 1/4\"",
      brand: "SMC",
      sku: "SMC-AR20-N02B-Z",
      mrp: 1800,
      sellingPrice: 1440,
      description:
        "SMC AR20 series air pressure regulator, 1/4\" NPT, 0.05-0.85 MPa range with gauge. Compact and lightweight for machine and panel mounting.",
      specifications: JSON.stringify({
        "Port Size": '1/4" NPT',
        "Pressure Range": "0.05 - 0.85 MPa",
        "Max Inlet Pressure": "1.0 MPa",
        "Flow Capacity": "500 L/min (ANR)",
        "Relief Function": "Yes",
        "Gauge Included": "Yes (0-1 MPa)",
        Fluid: "Air (filtered)",
        Weight: "225 g",
      }),
      categoryId: hydraulics.id,
      slug: "smc-ar20-n02b-z-pneumatic-pressure-regulator-14",
      inStock: true,
    },
    {
      name: "Parker Hydraulic Hose SAE 100R2 1/2\" ID 600mm",
      brand: "Parker",
      sku: "PAR-HH-R2-12-600",
      mrp: 880,
      sellingPrice: 704,
      description:
        "Parker SAE 100R2AT double wire braid hydraulic hose, 1/2\" ID, 600mm length with BSP fittings both ends. For high-pressure hydraulic systems.",
      specifications: JSON.stringify({
        "Inner Diameter": '1/2" (12.7 mm)',
        "Outer Diameter": "24.0 mm",
        Length: "600 mm",
        "Max Working Pressure": "275 bar",
        "Burst Pressure": "1100 bar",
        "Bend Radius": "127 mm",
        Standard: "SAE 100R2AT / ISO 1436-1",
        Fittings: '1/2" BSP male both ends',
      }),
      categoryId: hydraulics.id,
      slug: "parker-hydraulic-hose-sae-100r2-12-id-600mm",
      inStock: true,
    },
    {
      name: "Festo Air Filter Regulator Lubricator FRL Unit 1/2\"",
      brand: "Festo",
      sku: "FES-FRL-12-COMBO",
      mrp: 4200,
      sellingPrice: 3360,
      description:
        "Festo combination FRL unit (Filter + Regulator + Lubricator) for 1/2\" pneumatic systems. 40-micron filter, adjustable regulator, and oil-mist lubricator.",
      specifications: JSON.stringify({
        "Port Size": '1/2" BSP',
        "Filter Rating": "40 micron",
        "Pressure Range": "0.1 - 1.0 MPa",
        "Bowl Capacity (Filter)": "100 mL",
        "Bowl Capacity (Lubricator)": "100 mL",
        "Max Flow": "3000 L/min (ANR)",
        "Pressure Gauge": "Included",
        "Bracket": "Wall mount bracket included",
      }),
      categoryId: hydraulics.id,
      slug: "festo-air-filter-regulator-lubricator-frl-unit-12",
      inStock: true,
    },
  ];

  // Products for Belts, Chains & Gears
  const beltProducts = [
    {
      name: "Fenner A-Section V-Belt A50 (Inside Length 1270mm)",
      brand: "Fenner",
      sku: "FEN-VB-A50",
      mrp: 380,
      sellingPrice: 304,
      description:
        "Fenner A50 classical V-belt, A-section, 1270mm inside length. Oil and heat resistant. Suitable for general power transmission in fans, compressors, and pumps.",
      specifications: JSON.stringify({
        Section: "A",
        "Designation": "A50",
        "Inside Length": "1270 mm",
        "Top Width": "13 mm",
        Thickness: "8 mm",
        "Power Rating": "up to 4.5 kW",
        Material: "Rubber / Polyester cord",
        Standard: "IS 1370 / BS 3790",
      }),
      categoryId: belts.id,
      slug: "fenner-a-section-v-belt-a50-inside-length-1270mm",
      inStock: true,
    },
    {
      name: "Fenner SPC Section Wedge Belt SPC 2500",
      brand: "Fenner",
      sku: "FEN-WB-SPC2500",
      mrp: 1850,
      sellingPrice: 1480,
      description:
        "Fenner SPC2500 narrow section wedge belt for high-power compact drive systems. Wrapped rubber construction with aramid tensile cords.",
      specifications: JSON.stringify({
        Section: "SPC",
        "Inside Length": "2500 mm",
        "Top Width": "22 mm",
        Thickness: "18 mm",
        "Power Rating": "up to 40 kW",
        "Tensile Cord": "Aramid",
        Material: "Oil/Heat resistant rubber",
        Standard: "ISO 4184 / DIN 7753",
      }),
      categoryId: belts.id,
      slug: "fenner-spc-section-wedge-belt-spc-2500",
      inStock: true,
    },
    {
      name: "Renold Roller Chain 08B-1 (1/2\" Pitch) 5 Meters",
      brand: "Renold",
      sku: "REN-RC-08B1-5M",
      mrp: 2800,
      sellingPrice: 2240,
      description:
        "Renold 08B-1 simplex roller chain, 1/2\" pitch, 5 meter length with connecting link. For industrial conveyor and power transmission applications.",
      specifications: JSON.stringify({
        "Chain Number": "08B-1",
        Pitch: '1/2" (12.7 mm)',
        "Roller Diameter": "8.51 mm",
        "Inner Width": "7.75 mm",
        "Breaking Load": "18 kN",
        Length: "5 metres (394 links)",
        Material: "Carbon Steel",
        Standard: "ISO 606 / BS 228",
      }),
      categoryId: belts.id,
      slug: "renold-roller-chain-08b-1-12-pitch-5-meters",
      inStock: true,
    },
    {
      name: "Cast Iron Sprocket 08B 20-Tooth Pilot Bore",
      brand: "Fenner",
      sku: "FEN-SPR-08B-20T",
      mrp: 650,
      sellingPrice: 520,
      description:
        "Cast iron pilot bore sprocket for 08B-1 roller chain, 20-tooth. Pilot bore can be machined to required shaft size. Hub keyed and set-screw tapped.",
      specifications: JSON.stringify({
        "Chain Pitch": '1/2" (08B)',
        Teeth: "20",
        "Pitch Diameter": "81.07 mm",
        "Outside Diameter": "87.6 mm",
        "Pilot Bore": "10 mm",
        "Max Bore": "32 mm",
        Material: "Grade 200 Cast Iron",
        Hub: "Extended hub with keyway",
      }),
      categoryId: belts.id,
      slug: "cast-iron-sprocket-08b-20-tooth-pilot-bore",
      inStock: true,
    },
    {
      name: "Gates PowerGrip GT3 Timing Belt 5MGT-425",
      brand: "Gates",
      sku: "GAT-TB-5MGT-425",
      mrp: 1200,
      sellingPrice: 960,
      description:
        "Gates PowerGrip GT3 synchronous timing belt, 5mm pitch, 425mm pitch length, 15mm width. For precision positioning and servo motor drives.",
      specifications: JSON.stringify({
        "Belt Designation": "5MGT-425-15",
        Pitch: "5 mm (HTD/GT3)",
        "Pitch Length": "425 mm",
        Width: "15 mm",
        Teeth: "85",
        "Tensile Cord": "Fiberglass",
        Material: "Neoprene / Polyurethane",
        Standard: "ISO 13050",
      }),
      categoryId: belts.id,
      slug: "gates-powergip-gt3-timing-belt-5mgt-425",
      inStock: true,
    },
    {
      name: "Fenner Timing Pulley T5 20-Tooth 16mm Bore Aluminum",
      brand: "Fenner",
      sku: "FEN-TP-T5-20T-16B",
      mrp: 480,
      sellingPrice: 384,
      description:
        "Fenner aluminum timing pulley for T5 belt, 20 teeth, 16mm bore with keyway and set screw. Lightweight and corrosion resistant for servo and stepper drives.",
      specifications: JSON.stringify({
        "Belt Type": "T5 (5mm pitch)",
        Teeth: "20",
        "Pitch Diameter": "31.83 mm",
        "Flange Diameter": "38 mm",
        Bore: "16 mm",
        "Belt Width": "16 mm",
        Material: "Aluminum alloy",
        Hub: "Keyway + set screw",
      }),
      categoryId: belts.id,
      slug: "fenner-timing-pulley-t5-20-tooth-16mm-bore-aluminum",
      inStock: true,
    },
    {
      name: "Stainless Steel Flexible Coupling Jaw Type 19mm-24mm",
      brand: "KTR",
      sku: "KTR-JAW-19-24-SS",
      mrp: 1650,
      sellingPrice: 1320,
      description:
        "KTR ROTEX jaw coupling set (2 hubs + polyurethane spider), stainless steel hubs, 19mm and 24mm bore. Flexible, backlash-free coupling for motor-pump drives.",
      specifications: JSON.stringify({
        "Hub Material": "Stainless Steel 304",
        "Spider Material": "Polyurethane 92 Shore A",
        "Bore 1": "19 mm",
        "Bore 2": "24 mm",
        "Max Torque": "120 Nm",
        "Max Speed": "5000 rpm",
        "Misalignment Angular": "1°",
        Size: "ROTEX 24",
      }),
      categoryId: belts.id,
      slug: "stainless-steel-flexible-coupling-jaw-type-19mm-24mm",
      inStock: true,
    },
  ];

  // Products for Safety & PPE
  const safetyProducts = [
    {
      name: "3M Peltor Optime II Ear Muff 31dB SNR",
      brand: "3M",
      sku: "3M-1435-31DB",
      mrp: 2800,
      sellingPrice: 2240,
      description:
        "3M Peltor Optime II ear muffs with 31dB SNR for high-noise industrial environments. Soft, hygienic ear cushions with durable headband. CE certified.",
      specifications: JSON.stringify({
        "Noise Reduction": "31 dB SNR",
        "Cup Material": "ABS plastic",
        "Cushion Material": "Foam-filled PVC",
        "Headband": "Stainless steel",
        Weight: "215 g",
        "Frequency Range": "125 Hz - 8000 Hz",
        Standard: "EN 352-1 / IS 9167",
        Certification: "CE",
      }),
      categoryId: safety.id,
      slug: "3m-peltor-optime-ii-ear-muff-31db-snr",
      inStock: true,
    },
    {
      name: "Karam PN 501 Full Body Safety Harness Class A",
      brand: "Karam",
      sku: "KAR-PN501-FBH",
      mrp: 3500,
      sellingPrice: 2800,
      description:
        "Karam PN 501 full body fall arrest harness with front and back D-rings. Polyester webbing, Class A. For working at heights above 1.8 metres.",
      specifications: JSON.stringify({
        Class: "A (Fall Arrest)",
        "Webbing Material": "Polyester",
        "D-Ring Positions": "Front + Back (dorsal)",
        "Max User Weight": "140 kg",
        "Breaking Strength": "> 22 kN",
        "Webbing Width": "45 mm",
        Standard: "IS 3521 / EN 361",
        Color: "Blue/Black",
      }),
      categoryId: safety.id,
      slug: "karam-pn-501-full-body-safety-harness-class-a",
      inStock: true,
    },
    {
      name: "3M 6200 Half Face Respirator Medium with OV/P100 Cartridges",
      brand: "3M",
      sku: "3M-6200-OVNR100",
      mrp: 3200,
      sellingPrice: 2560,
      description:
        "3M 6200 half face respirator kit, medium size, with 60926 OV/N100 cartridges. For protection against organic vapors, gases, and particulates.",
      specifications: JSON.stringify({
        Size: "Medium",
        "Cartridge Type": "60926 OV/P100",
        "Protection Level": "P100 + Organic Vapors",
        "Filter Efficiency": "99.97% @ 0.3 micron",
        Material: "Silicone face seal",
        "Cool Flow Valve": "Yes",
        Standard: "NIOSH / IS 15321",
        Certification: "CE / NIOSH",
      }),
      categoryId: safety.id,
      slug: "3m-6200-half-face-respirator-medium-with-ovp100-cartridges",
      inStock: true,
    },
    {
      name: "Karam Safety Helmet ISI Marked Ratchet Type Yellow",
      brand: "Karam",
      sku: "KAR-SH-ISI-R-YLW",
      mrp: 580,
      sellingPrice: 464,
      description:
        "Karam ISI marked industrial safety helmet with ratchet adjustment. HDPE shell, 6-point nylon suspension. Ventilated slots for comfort.",
      specifications: JSON.stringify({
        Material: "HDPE",
        Suspension: "6-point nylon",
        Adjustment: "Ratchet knob",
        "Ventilation": "Yes",
        Weight: "380 g",
        Color: "Yellow",
        "Temp Rating": "-20°C to +50°C",
        Standard: "IS 2925 / EN 397",
      }),
      categoryId: safety.id,
      slug: "karam-safety-helmet-isi-marked-ratchet-type-yellow",
      inStock: true,
    },
    {
      name: "3M VHB 400 Cut Resistant Gloves Level 4 Size L",
      brand: "3M",
      sku: "3M-CRG-L4-L",
      mrp: 650,
      sellingPrice: 520,
      description:
        "3M cut resistant gloves, EN 388 cut level 4, size Large. HPPE fiber liner with polyurethane coating. For handling sheet metal, glass, and sharp components.",
      specifications: JSON.stringify({
        "Cut Resistance": "EN 388 Level 4",
        Size: "Large (9)",
        Material: "HPPE + Nylon",
        Coating: "Polyurethane (palm)",
        Grip: "Smooth PU for dry/oily",
        "EN 388 Rating": "4X42B",
        Standard: "EN 388:2016",
        "Touch Screen": "No",
      }),
      categoryId: safety.id,
      slug: "3m-vhb-400-cut-resistant-gloves-level-4-size-l",
      inStock: true,
    },
    {
      name: "Karam Safety Shoes Steel Toe Cap S1P Size 8",
      brand: "Karam",
      sku: "KAR-SS-S1P-UK8",
      mrp: 2200,
      sellingPrice: 1760,
      description:
        "Karam safety shoes with steel toe cap (200J), steel midsole, and anti-static properties. S1P rated, oil-resistant PU/rubber sole. Comfortable leather upper.",
      specifications: JSON.stringify({
        Standard: "EN ISO 20345:2011 S1P",
        "Toe Protection": "200 J steel cap",
        Midsole: "Steel anti-penetration",
        "Sole Material": "PU/Rubber",
        Upper: "Full grain leather",
        "Anti-Static": "Yes (< 1000 MΩ)",
        "Oil Resistant": "Yes",
        Size: "UK 8 / EU 42",
      }),
      categoryId: safety.id,
      slug: "karam-safety-shoes-steel-toe-cap-s1p-size-8",
      inStock: true,
    },
    {
      name: "Honeywell Uvex Splash-proof Safety Goggles Clear",
      brand: "Honeywell",
      sku: "HON-UVX-SPGOG-CLR",
      mrp: 480,
      sellingPrice: 384,
      description:
        "Honeywell Uvex chemical splash-proof safety goggles with clear anti-fog lens. Indirect ventilation for chemical handling, labs, and grinding operations.",
      specifications: JSON.stringify({
        "Lens Color": "Clear",
        "Lens Material": "Polycarbonate",
        "Anti-Fog": "Yes (Uvextreme coating)",
        "UV Protection": "UV400",
        Ventilation: "Indirect (chemical splash)",
        Frame: "Soft PVC",
        Weight: "75 g",
        Standard: "EN 166 / IS 5983",
      }),
      categoryId: safety.id,
      slug: "honeywell-uvex-splash-proof-safety-goggles-clear",
      inStock: true,
    },
  ];

  // Products for Motors & Pumps
  const motorProducts = [
    {
      name: "Crompton 1.5 HP Single Phase Induction Motor 1440 RPM",
      brand: "Crompton",
      sku: "CRO-IM-15HP-1PH",
      mrp: 8500,
      sellingPrice: 6800,
      description:
        "Crompton 1.5 HP single-phase capacitor-start induction motor, 1440 RPM, B3 foot mounting. IE2 efficiency class. For water pumps, compressors, and fans.",
      specifications: JSON.stringify({
        Power: "1.5 HP (1.1 kW)",
        "Phase": "Single Phase",
        Speed: "1440 RPM",
        Voltage: "220-240V AC",
        Efficiency: "IE2",
        "Mounting": "B3 (Foot mount)",
        "Frame Size": "90L",
        "IP Rating": "IP55",
      }),
      categoryId: motors.id,
      slug: "crompton-15-hp-single-phase-induction-motor-1440-rpm",
      inStock: true,
    },
    {
      name: "Kirloskar 5 HP 3-Phase Centrifugal Pump Monoblock",
      brand: "Kirloskar",
      sku: "KIR-CP-5HP-3PH-MB",
      mrp: 18500,
      sellingPrice: 14800,
      description:
        "Kirloskar 5 HP 3-phase monoblock centrifugal pump for clean water. Max head 35m, max flow 500 LPM. Direct-coupled motor and pump on common base.",
      specifications: JSON.stringify({
        Power: "5 HP (3.7 kW)",
        Phase: "3 Phase",
        "Max Head": "35 m",
        "Max Flow": "500 LPM",
        Inlet: '2" BSP',
        Outlet: '1.5" BSP',
        Impeller: "Bronze",
        "Body Material": "Cast Iron",
      }),
      categoryId: motors.id,
      slug: "kirloskar-5-hp-3-phase-centrifugal-pump-monoblock",
      inStock: true,
    },
    {
      name: "Crompton 2HP 3-Phase AC Induction Motor IE3 1450RPM B3",
      brand: "Crompton",
      sku: "CRO-IM-2HP-3PH-IE3",
      mrp: 7800,
      sellingPrice: 6240,
      description:
        "Crompton 2HP 3-phase IE3 premium efficiency induction motor, 1450 RPM, B3 foot mounting, 415V. Robust TEFC design for continuous duty industrial use.",
      specifications: JSON.stringify({
        Power: "2 HP (1.5 kW)",
        Phase: "3 Phase",
        Speed: "1450 RPM",
        Voltage: "415V AC",
        Efficiency: "IE3 (Premium)",
        Mounting: "B3 (Foot mount)",
        "Frame Size": "90L",
        "IP Rating": "IP55 TEFC",
      }),
      categoryId: motors.id,
      slug: "crompton-2hp-3-phase-ac-induction-motor-ie3-1450rpm-b3",
      inStock: true,
    },
    {
      name: "Grundfos CM3-5 Stainless Steel Horizontal Multistage Pump",
      brand: "Grundfos",
      sku: "GRU-CM3-5-SS",
      mrp: 22000,
      sellingPrice: 17600,
      description:
        "Grundfos CM3-5 horizontal multistage centrifugal pump, stainless steel body. Max head 55m, flow 3 m³/h. For water supply, pressure boosting, and filtration.",
      specifications: JSON.stringify({
        Stages: "5",
        "Max Flow": "3 m³/h (50 LPM)",
        "Max Head": "55 m",
        Power: "0.55 kW",
        Voltage: "1x220-240V / 3x380-415V",
        "Body Material": "AISI 304 Stainless Steel",
        Impeller: "AISI 304",
        "Max Temp": "90°C",
      }),
      categoryId: motors.id,
      slug: "grundfos-cm3-5-stainless-steel-horizontal-multistage-pump",
      inStock: true,
    },
    {
      name: "Kirloskar 0.5HP Submersible Pump Borewell 3-Wire",
      brand: "Kirloskar",
      sku: "KIR-SUB-05HP-3W",
      mrp: 9500,
      sellingPrice: 7600,
      description:
        "Kirloskar 0.5 HP submersible borewell pump, 3-wire, single phase 220V. Max head 45m, suitable for 4\" borewell. Stainless steel body with NORYL impeller.",
      specifications: JSON.stringify({
        Power: "0.5 HP (370 W)",
        Phase: "Single Phase",
        Voltage: "220V AC",
        "Max Head": "45 m",
        "Max Flow": "100 LPM",
        "Min Borewell": '4"',
        Body: "Stainless Steel AISI 304",
        "Motor Type": "3-Wire (External capacitor)",
      }),
      categoryId: motors.id,
      slug: "kirloskar-05hp-submersible-pump-borewell-3-wire",
      inStock: true,
    },
    {
      name: "Crompton Gear Reduction Motor 1HP 60RPM 3-Phase",
      brand: "Crompton",
      sku: "CRO-GRM-1HP-60RPM",
      mrp: 14500,
      sellingPrice: 11600,
      description:
        "Crompton helical gear motor, 1 HP input, 60 RPM output, 3-phase 415V, gear ratio 24:1. Compact inline design for conveyor, agitator, and mixer drives.",
      specifications: JSON.stringify({
        "Input Power": "1 HP (0.75 kW)",
        "Output Speed": "60 RPM",
        "Gear Ratio": "24:1",
        Phase: "3 Phase 415V",
        "Gear Type": "Helical",
        Mounting: "B3 foot mount",
        "Output Torque": "120 Nm",
        "IP Rating": "IP55",
      }),
      categoryId: motors.id,
      slug: "crompton-gear-reduction-motor-1hp-60rpm-3-phase",
      inStock: true,
    },
    {
      name: "ABB ACS310 5.5kW Variable Frequency Drive 3-Phase",
      brand: "ABB",
      sku: "ABB-ACS310-5P5KW",
      mrp: 28000,
      sellingPrice: 22400,
      description:
        "ABB ACS310 5.5kW variable frequency drive for motor speed control. 3-phase 415V input/output, built-in EMC filter and keypad. For fans, pumps, and conveyors.",
      specifications: JSON.stringify({
        Power: "5.5 kW (7.5 HP)",
        "Input Voltage": "3-phase 380-415V AC",
        "Output Frequency": "0-500 Hz",
        "Motor Current": "13.8 A",
        "EMC Filter": "Built-in C2",
        "Control Panel": "Integral keypad with display",
        "IP Rating": "IP20",
        Standard: "IEC 61800-5-1 / CE",
      }),
      categoryId: motors.id,
      slug: "abb-acs310-55kw-variable-frequency-drive-3-phase",
      inStock: true,
    },
  ];

  // Insert all products
  const allProductData = [
    ...bearingProducts,
    ...fastenerProducts,
    ...electricalProducts,
    ...toolProducts,
    ...hydraulicProducts,
    ...beltProducts,
    ...safetyProducts,
    ...motorProducts,
  ];

  const createdProducts = await Promise.all(
    allProductData.map((product) =>
      prisma.product.create({
        data: product,
      })
    )
  );

  console.log(`Created ${createdProducts.length} products.`);
  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
