import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

const categories = [
  { name: "Bearings & Power Transmission", slug: "bearings-power-transmission", icon: "🔩" },
  { name: "Electrical & Wiring", slug: "electrical-wiring", icon: "⚡" },
  { name: "Hand Tools", slug: "hand-tools", icon: "🛠️" },
  { name: "Safety & PPE", slug: "safety-ppe", icon: "🦺" },
  { name: "Pumps & Motors", slug: "pumps-motors", icon: "🏭" },
  { name: "Fasteners & Hardware", slug: "fasteners-hardware", icon: "🔧" },
  { name: "Cutting Tools", slug: "cutting-tools", icon: "⚙️" },
  { name: "Instrumentation & Controls", slug: "instrumentation-controls", icon: "💧" },
];

const products = [
  // Bearings & Power Transmission
  {
    name: "SKF 6205 Deep Groove Ball Bearing",
    slug: "skf-6205-deep-groove-ball-bearing",
    brand: "SKF",
    sku: "SKF-6205-2RS",
    description: "SKF 6205 deep groove ball bearing with rubber seals on both sides. Suitable for electric motors, pumps and general machinery. Inner diameter 25mm, outer diameter 52mm, width 15mm.",
    mrp: 850,
    sellingPrice: 680,
    categorySlug: "bearings-power-transmission",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "SKF 6306 Single Row Ball Bearing",
    slug: "skf-6306-single-row-ball-bearing",
    brand: "SKF",
    sku: "SKF-6306-2Z",
    description: "SKF 6306 single row deep groove ball bearing with metal shields. High load capacity and long service life. ID 30mm, OD 72mm, Width 19mm.",
    mrp: 1200,
    sellingPrice: 950,
    categorySlug: "bearings-power-transmission",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Fenner B-Section V-Belt B68",
    slug: "fenner-b-section-v-belt-b68",
    brand: "Fenner",
    sku: "FEN-VBELT-B68",
    description: "Fenner classic B-section V-belt, B68 size (1727mm effective length). Oil and heat resistant. Suitable for industrial drives, compressors and agricultural equipment.",
    mrp: 420,
    sellingPrice: 330,
    categorySlug: "bearings-power-transmission",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "SKF 22208 E Spherical Roller Bearing",
    slug: "skf-22208-e-spherical-roller-bearing",
    brand: "SKF",
    sku: "SKF-22208-E",
    description: "SKF 22208 E spherical roller bearing for heavy-duty applications. Self-aligning capability, suitable for vibratory equipment, conveyors and crushers. ID 40mm, OD 80mm.",
    mrp: 3200,
    sellingPrice: 2560,
    categorySlug: "bearings-power-transmission",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Fenner Taper Lock Pulley 4\" SPA",
    slug: "fenner-taper-lock-pulley-4-spa",
    brand: "Fenner",
    sku: "FEN-TLP-4SPA",
    description: "Fenner 4-inch single groove SPA section taper lock pulley. Cast iron construction. Easy installation and removal with taper lock bush system.",
    mrp: 1850,
    sellingPrice: 1480,
    categorySlug: "bearings-power-transmission",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "SKF LGHP 2 High Performance Grease 400g",
    slug: "skf-lghp2-high-performance-grease-400g",
    brand: "SKF",
    sku: "SKF-LGHP2-400",
    description: "SKF LGHP 2 high performance mineral grease for electric motor bearings. Temperature range -30°C to +150°C. 400g cartridge.",
    mrp: 950,
    sellingPrice: 760,
    categorySlug: "bearings-power-transmission",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Fenner A-Section V-Belt A42",
    slug: "fenner-a-section-v-belt-a42",
    brand: "Fenner",
    sku: "FEN-VBELT-A42",
    description: "Fenner classic A-section V-belt A42 size (1092mm effective length). Suitable for light-duty industrial drives, fans and blowers.",
    mrp: 280,
    sellingPrice: 210,
    categorySlug: "bearings-power-transmission",
    inStock: true,
    imageUrl: "",
  },

  // Electrical & Wiring
  {
    name: "Havells 6A MCB Single Pole C-Curve",
    slug: "havells-6a-mcb-single-pole-c-curve",
    brand: "Havells",
    sku: "HAV-MCB-6A-SP-C",
    description: "Havells 6 Ampere single pole miniature circuit breaker, C-curve. Breaking capacity 10kA. Suitable for residential and commercial electrical panels.",
    mrp: 320,
    sellingPrice: 255,
    categorySlug: "electrical-wiring",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Schneider Electric 32A RCCB 30mA",
    slug: "schneider-electric-32a-rccb-30ma",
    brand: "Schneider",
    sku: "SCH-RCCB-32A-30mA",
    description: "Schneider Electric iID 32A 2-pole RCCB with 30mA sensitivity. Provides protection against earth fault and shock. Easy installation on DIN rail.",
    mrp: 1850,
    sellingPrice: 1480,
    categorySlug: "electrical-wiring",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Havells 2.5 Sq.mm FR PVC Wire 90m",
    slug: "havells-2-5sqmm-fr-pvc-wire-90m",
    brand: "Havells",
    sku: "HAV-WIRE-2.5-90M",
    description: "Havells Lifeline Plus 2.5 sq.mm FR PVC insulated single core copper wire, 90 metre coil. Suitable for domestic wiring, high current capacity 23A.",
    mrp: 2400,
    sellingPrice: 1920,
    categorySlug: "electrical-wiring",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Schneider Electric 63A MCCB 3-Pole",
    slug: "schneider-electric-63a-mccb-3-pole",
    brand: "Schneider",
    sku: "SCH-MCCB-63A-3P",
    description: "Schneider Electric EasyPact CVS 63A 3-pole moulded case circuit breaker. Breaking capacity 36kA at 415V. For motor and feeder protection in industrial panels.",
    mrp: 8500,
    sellingPrice: 6800,
    categorySlug: "electrical-wiring",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Havells 16A Industrial Socket 3-Pin",
    slug: "havells-16a-industrial-socket-3-pin",
    brand: "Havells",
    sku: "HAV-SOCK-16A-3P",
    description: "Havells 16A 3-pin industrial power socket, splash-proof IP44. Heavy-duty polycarbonate body. Suitable for power tools and industrial equipment.",
    mrp: 680,
    sellingPrice: 545,
    categorySlug: "electrical-wiring",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Bosch 1.5 Sq.mm Flexible Wire 100m",
    slug: "bosch-1-5sqmm-flexible-wire-100m",
    brand: "Bosch",
    sku: "BSH-WIRE-1.5-100M",
    description: "Bosch flexible multi-strand 1.5 sq.mm copper wire with PVC insulation. 100m drum. Suitable for control wiring and instrumentation circuits.",
    mrp: 1800,
    sellingPrice: 1440,
    categorySlug: "electrical-wiring",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Schneider 40A Contactor 3-Phase LC1D40",
    slug: "schneider-40a-contactor-3-phase-lc1d40",
    brand: "Schneider",
    sku: "SCH-LC1D40-3P",
    description: "Schneider Electric TeSys D series 40A 3-phase contactor LC1D40. 220V AC coil. For motor starting, reversing and capacitor bank switching.",
    mrp: 3200,
    sellingPrice: 2560,
    categorySlug: "electrical-wiring",
    inStock: true,
    imageUrl: "",
  },

  // Hand Tools
  {
    name: "Taparia Double Open End Spanner Set 8-Piece",
    slug: "taparia-double-open-end-spanner-set-8pc",
    brand: "Taparia",
    sku: "TAP-DOES-8PC",
    description: "Taparia 8-piece double open end spanner set in sizes 6x7, 8x9, 10x11, 12x13, 14x15, 16x17, 18x19, 20x22mm. Drop-forged chrome vanadium steel, chrome plated.",
    mrp: 1200,
    sellingPrice: 920,
    categorySlug: "hand-tools",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Stanley FatMax Claw Hammer 20oz",
    slug: "stanley-fatmax-claw-hammer-20oz",
    brand: "Stanley",
    sku: "STN-HAMMER-20OZ",
    description: "Stanley FatMax anti-vibe claw hammer 20oz (567g). Forged steel head with anti-vibe technology reduces vibration by 70%. Bi-material grip for comfort.",
    mrp: 1650,
    sellingPrice: 1320,
    categorySlug: "hand-tools",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Taparia Combination Plier 8-inch",
    slug: "taparia-combination-plier-8-inch",
    brand: "Taparia",
    sku: "TAP-CP-8",
    description: "Taparia 8-inch combination plier with PVC sleeve handles. Drop-forged alloy steel, induction hardened cutting edges. Suitable for gripping, bending and cutting wire.",
    mrp: 480,
    sellingPrice: 380,
    categorySlug: "hand-tools",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Bosch Heavy Duty Torque Wrench 1/2\" Drive",
    slug: "bosch-torque-wrench-half-inch-drive",
    brand: "Bosch",
    sku: "BSH-TW-0.5DR",
    description: "Bosch 1/2-inch drive click-type torque wrench, 28-210 Nm range. Reversible ratchet head. Dual-scale graduation in Nm and ft-lbs. Includes storage case.",
    mrp: 4200,
    sellingPrice: 3360,
    categorySlug: "hand-tools",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Stanley 6-Piece Screwdriver Set",
    slug: "stanley-6-piece-screwdriver-set",
    brand: "Stanley",
    sku: "STN-SD-6PC",
    description: "Stanley 6-piece screwdriver set including 3 Phillips (PH1, PH2, PH3) and 3 slotted screwdrivers. Chrome vanadium tips, soft grip handles for maximum torque.",
    mrp: 850,
    sellingPrice: 680,
    categorySlug: "hand-tools",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Taparia Allen Key Set Metric 9-Piece",
    slug: "taparia-allen-key-set-metric-9pc",
    brand: "Taparia",
    sku: "TAP-AKS-9PC-M",
    description: "Taparia 9-piece metric allen/hex key set in sizes 1.5, 2, 2.5, 3, 4, 5, 6, 8, 10mm. Chrome vanadium steel, long arm design for extra torque.",
    mrp: 650,
    sellingPrice: 520,
    categorySlug: "hand-tools",
    inStock: true,
    imageUrl: "",
  },

  // Safety & PPE
  {
    name: "Karam PN501 Safety Helmet ISI Marked",
    slug: "karam-pn501-safety-helmet-isi-marked",
    brand: "Karam",
    sku: "KRM-PN501-YLW",
    description: "Karam PN501 industrial safety helmet, ISI marked IS:2925. HDPE shell with ratchet adjustment system. Weight 320g. Suitable for construction, mining and industrial use.",
    mrp: 580,
    sellingPrice: 465,
    categorySlug: "safety-ppe",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "3M 9502+ N95 Respirator Mask Pack of 10",
    slug: "3m-9502-plus-n95-respirator-pack-10",
    brand: "3M",
    sku: "3M-9502-10PK",
    description: "3M 9502+ N95 particulate respirator with valve. Filters at least 95% of airborne particles. Lightweight and foldable design. Pack of 10 masks.",
    mrp: 1200,
    sellingPrice: 950,
    categorySlug: "safety-ppe",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Karam Full Body Safety Harness PN303",
    slug: "karam-pn303-full-body-safety-harness",
    brand: "Karam",
    sku: "KRM-PN303",
    description: "Karam PN303 full body safety harness with energy absorbing lanyard. CE certified, EN361 compliant. D-ring on back and chest. Suitable for work at height.",
    mrp: 3800,
    sellingPrice: 3040,
    categorySlug: "safety-ppe",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "3M Chemical Resistant Safety Gloves L",
    slug: "3m-chemical-resistant-safety-gloves-l",
    brand: "3M",
    sku: "3M-GLV-CHEM-L",
    description: "3M chemical resistant nitrile gloves, size Large. 0.3mm thickness, superior dexterity. Resistant to oils, fuels and many chemicals. Pack of 100 pairs.",
    mrp: 2200,
    sellingPrice: 1760,
    categorySlug: "safety-ppe",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Karam Safety Shoes Steel Toe Cap Size 8",
    slug: "karam-safety-shoes-steel-toe-cap-size-8",
    brand: "Karam",
    sku: "KRM-SHOE-8",
    description: "Karam safety shoes with steel toe cap, IS:15298 compliant. Anti-slip PU sole, puncture-resistant midsole. Leather upper with padded collar. Size 8.",
    mrp: 2800,
    sellingPrice: 2240,
    categorySlug: "safety-ppe",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "3M Peltor Earmuff Hearing Protection",
    slug: "3m-peltor-earmuff-hearing-protection",
    brand: "3M",
    sku: "3M-PELTOR-H10A",
    description: "3M Peltor Optime 105 over-the-head earmuffs. NRR 30dB noise reduction. Suitable for heavy industrial environments, stamping, grinding and metal fabrication.",
    mrp: 1850,
    sellingPrice: 1480,
    categorySlug: "safety-ppe",
    inStock: true,
    imageUrl: "",
  },

  // Pumps & Motors
  {
    name: "Crompton 0.5HP Self-Priming Centrifugal Pump",
    slug: "crompton-0-5hp-self-priming-centrifugal-pump",
    brand: "Crompton",
    sku: "CRM-PUMP-0.5HP-SP",
    description: "Crompton 0.5HP single-phase self-priming centrifugal pump. Max head 30m, flow rate 60 LPM. Cast iron body. Suitable for domestic water supply and irrigation.",
    mrp: 4800,
    sellingPrice: 3840,
    categorySlug: "pumps-motors",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Crompton 1HP Submersible Pump 1-Phase",
    slug: "crompton-1hp-submersible-pump-1-phase",
    brand: "Crompton",
    sku: "CRM-SUBPUMP-1HP",
    description: "Crompton 1HP single-phase submersible pump for borewell. Max head 45m, discharge 2880 LPH. Stainless steel body. Suitable for 4-inch borewell.",
    mrp: 8500,
    sellingPrice: 6800,
    categorySlug: "pumps-motors",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Crompton 2HP 3-Phase Induction Motor 4-Pole",
    slug: "crompton-2hp-3-phase-induction-motor-4-pole",
    brand: "Crompton",
    sku: "CRM-MOTOR-2HP-3P",
    description: "Crompton 2HP (1.5kW) 3-phase squirrel cage induction motor, 4-pole 1440 RPM. IE2 efficiency class. Frame size 90L. Foot mounted, IP55 protection.",
    mrp: 9200,
    sellingPrice: 7360,
    categorySlug: "pumps-motors",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Bosch 5HP 3-Phase Induction Motor",
    slug: "bosch-5hp-3-phase-induction-motor",
    brand: "Bosch",
    sku: "BSH-MOTOR-5HP-3P",
    description: "Bosch 5HP (3.7kW) 3-phase AC induction motor, 4-pole 1440 RPM. IE2 efficiency. B3 foot mounting. Suitable for compressors, conveyors and industrial machinery.",
    mrp: 18500,
    sellingPrice: 14800,
    categorySlug: "pumps-motors",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Crompton 10HP Monoblock Pump 3-Phase",
    slug: "crompton-10hp-monoblock-pump-3-phase",
    brand: "Crompton",
    sku: "CRM-MONO-10HP-3P",
    description: "Crompton 10HP 3-phase monoblock centrifugal pump. Max head 60m, flow 1200 LPM. Suitable for agriculture, industrial water supply and firefighting systems.",
    mrp: 32000,
    sellingPrice: 25600,
    categorySlug: "pumps-motors",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Crompton 0.25HP Mini Pump Single Phase",
    slug: "crompton-0-25hp-mini-pump-single-phase",
    brand: "Crompton",
    sku: "CRM-PUMP-0.25HP",
    description: "Crompton 0.25HP mini centrifugal pump for clean water transfer. Max head 15m, flow 30 LPM. Compact design, suitable for small gardens and tank filling.",
    mrp: 2800,
    sellingPrice: 2240,
    categorySlug: "pumps-motors",
    inStock: true,
    imageUrl: "",
  },

  // Fasteners & Hardware
  {
    name: "M10 x 50mm Hex Bolt Zinc Plated Grade 8.8 (Pack 50)",
    slug: "m10-x-50mm-hex-bolt-zinc-plated-grade-8-8-pack-50",
    brand: "Bosch",
    sku: "BSH-BOLT-M10x50-50PK",
    description: "M10 x 50mm hex head bolt, Grade 8.8 zinc plated. High tensile strength for structural and machine assembly. Pack of 50 pieces with matching nuts and washers.",
    mrp: 680,
    sellingPrice: 545,
    categorySlug: "fasteners-hardware",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "M12 Stainless Steel Anchor Bolt Pack 20",
    slug: "m12-stainless-steel-anchor-bolt-pack-20",
    brand: "Stanley",
    sku: "STN-ANCHOR-M12-20PK",
    description: "M12 stainless steel expansion anchor bolt for concrete and masonry. Suitable for machine base mounting and structural fixing. Pack of 20 pieces.",
    mrp: 1200,
    sellingPrice: 960,
    categorySlug: "fasteners-hardware",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "3M VHB Double Sided Tape 25mm x 3m",
    slug: "3m-vhb-double-sided-tape-25mm-3m",
    brand: "3M",
    sku: "3M-VHB-25x3M",
    description: "3M VHB (Very High Bond) double-sided acrylic foam tape. 25mm wide, 3m length. Provides permanent structural bonding for metal, glass and plastics. Replaces welding and rivets.",
    mrp: 850,
    sellingPrice: 680,
    categorySlug: "fasteners-hardware",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "M8 Hex Nut Zinc Plated Grade 8 (Pack 100)",
    slug: "m8-hex-nut-zinc-plated-grade-8-pack-100",
    brand: "Taparia",
    sku: "TAP-NUT-M8-100PK",
    description: "M8 zinc plated hex nuts, Grade 8. High strength for mechanical and structural fastening. Pack of 100 pieces. Conforms to DIN 934 standard.",
    mrp: 280,
    sellingPrice: 220,
    categorySlug: "fasteners-hardware",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Stainless Steel Spring Washers M10 Pack 100",
    slug: "stainless-steel-spring-washers-m10-pack-100",
    brand: "Stanley",
    sku: "STN-WASH-M10-SS-100",
    description: "M10 stainless steel 316 grade spring (lock) washers. Prevents bolt loosening under vibration. Suitable for outdoor, marine and chemical environments. Pack of 100.",
    mrp: 380,
    sellingPrice: 305,
    categorySlug: "fasteners-hardware",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Self-Drilling Tek Screws 5.5 x 25mm Pack 200",
    slug: "self-drilling-tek-screws-5-5x25mm-pack-200",
    brand: "Bosch",
    sku: "BSH-TEK-5.5x25-200PK",
    description: "Bosch zinc-plated carbon steel self-drilling tek screws 5.5 x 25mm. Drill and tap in one operation on thin metal sheets. Hexagonal washer head. Pack of 200.",
    mrp: 450,
    sellingPrice: 360,
    categorySlug: "fasteners-hardware",
    inStock: true,
    imageUrl: "",
  },

  // Cutting Tools
  {
    name: "Bosch HSS-G Drill Bit Set 13-Piece",
    slug: "bosch-hss-g-drill-bit-set-13pc",
    brand: "Bosch",
    sku: "BSH-DRILLSET-13PC",
    description: "Bosch HSS-G 13-piece metal drill bit set, 1.5-6.5mm. Ground from solid high speed steel for superior precision. Suitable for drilling steel, cast iron, copper and aluminium.",
    mrp: 1650,
    sellingPrice: 1320,
    categorySlug: "cutting-tools",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "3M Cubitron II Grinding Wheel 115mm x 6mm",
    slug: "3m-cubitron-ii-grinding-wheel-115mm-6mm",
    brand: "3M",
    sku: "3M-GW-115x6",
    description: "3M Cubitron II precision-shaped grain grinding wheel 115mm x 6mm x 22.23mm. Type 27 depressed center. Cuts up to 35% faster than conventional wheels. For angle grinders.",
    mrp: 380,
    sellingPrice: 305,
    categorySlug: "cutting-tools",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Bosch TCT Circular Saw Blade 185mm 40T",
    slug: "bosch-tct-circular-saw-blade-185mm-40t",
    brand: "Bosch",
    sku: "BSH-CSB-185-40T",
    description: "Bosch Standard for Wood 185mm x 40T TCT circular saw blade. Bore 30mm, kerf 2.6mm. Tungsten carbide tips for clean cuts in wood, plywood and fibre boards.",
    mrp: 850,
    sellingPrice: 680,
    categorySlug: "cutting-tools",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Stanley HSS Metal Hacksaw Blade Pack 10",
    slug: "stanley-hss-metal-hacksaw-blade-pack-10",
    brand: "Stanley",
    sku: "STN-HACKSAW-18TPI-10PK",
    description: "Stanley 12-inch bi-metal hacksaw blade, 18 TPI. High speed steel cutting edge welded to flexible spring steel back. For cutting mild steel, copper and aluminium. Pack of 10.",
    mrp: 420,
    sellingPrice: 335,
    categorySlug: "cutting-tools",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Bosch SDS-Plus Masonry Drill Bit 12mm x 150mm",
    slug: "bosch-sds-plus-masonry-drill-bit-12mm-150mm",
    brand: "Bosch",
    sku: "BSH-SDS-12x150",
    description: "Bosch CYL-3 SDS-Plus masonry drill bit 12mm x 150mm. Carbide tip with 4 cutting edges. For percussion drilling in concrete, brick, stone and masonry.",
    mrp: 680,
    sellingPrice: 545,
    categorySlug: "cutting-tools",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "3M Scotch-Brite Non-Woven Abrasive Disc 115mm",
    slug: "3m-scotch-brite-non-woven-abrasive-disc-115mm",
    brand: "3M",
    sku: "3M-SB-NW-115",
    description: "3M Scotch-Brite non-woven abrasive disc 115mm, Medium grade. For surface conditioning, deburring and finishing of metals. Flexible, conforms to complex shapes. Pack of 10.",
    mrp: 650,
    sellingPrice: 520,
    categorySlug: "cutting-tools",
    inStock: true,
    imageUrl: "",
  },

  // Instrumentation & Controls
  {
    name: "Schneider Zelio Logic SR3B261BD Smart Relay",
    slug: "schneider-zelio-logic-sr3b261bd-smart-relay",
    brand: "Schneider",
    sku: "SCH-SR3B261BD",
    description: "Schneider Electric Zelio Logic smart relay with 26 I/O (16 inputs, 10 relay outputs). 24V DC power supply. Programmable via PC or keypad. For simple automation tasks.",
    mrp: 18500,
    sellingPrice: 14800,
    categorySlug: "instrumentation-controls",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Bosch 0-10 Bar Pressure Gauge 100mm Glycerine",
    slug: "bosch-0-10-bar-pressure-gauge-100mm-glycerine",
    brand: "Bosch",
    sku: "BSH-PG-0-10B-100",
    description: "Bourdon tube pressure gauge 0-10 Bar, 100mm dial, glycerine filled. 1/2-inch BSP bottom connection. Stainless steel Bourdon tube and wetted parts. Suitable for hydraulic and pneumatic systems.",
    mrp: 1200,
    sellingPrice: 960,
    categorySlug: "instrumentation-controls",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Schneider XB5 Push Button Station 2-Button",
    slug: "schneider-xb5-push-button-station-2-button",
    brand: "Schneider",
    sku: "SCH-XB5-PB-2BTN",
    description: "Schneider Electric XB5 push button station with start (green) and stop (red) buttons. IP65 rated plastic enclosure. 22mm operators. For motor start/stop control.",
    mrp: 1850,
    sellingPrice: 1480,
    categorySlug: "instrumentation-controls",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "SKF TKDT 10 Digital Thermometer",
    slug: "skf-tkdt-10-digital-thermometer",
    brand: "SKF",
    sku: "SKF-TKDT10",
    description: "SKF TKDT 10 digital thermometer for bearing temperature monitoring. Range -50°C to 200°C. K-type thermocouple with 1m probe cable. Backlit LCD display.",
    mrp: 3800,
    sellingPrice: 3040,
    categorySlug: "instrumentation-controls",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Havells Digital Energy Meter Single Phase",
    slug: "havells-digital-energy-meter-single-phase",
    brand: "Havells",
    sku: "HAV-DEM-1P",
    description: "Havells single-phase digital energy meter with LCD display. Class 1 accuracy, direct connected up to 63A. Measures kWh, kW, voltage, current and power factor.",
    mrp: 1650,
    sellingPrice: 1320,
    categorySlug: "instrumentation-controls",
    inStock: true,
    imageUrl: "",
  },
  {
    name: "Schneider ATV320 Variable Speed Drive 0.75kW",
    slug: "schneider-atv320-variable-speed-drive-0-75kw",
    brand: "Schneider",
    sku: "SCH-ATV320-0.75KW",
    description: "Schneider Electric Altivar 320 variable speed drive for 3-phase induction motor, 0.75kW (1HP). Input 200-240V 1-phase or 380-500V 3-phase. Integrated EMC filter and braking transistor.",
    mrp: 14500,
    sellingPrice: 11600,
    categorySlug: "instrumentation-controls",
    inStock: true,
    imageUrl: "",
  },
];

export async function POST() {
  try {
    let categoryCount = 0;
    let productCount = 0;

    // Create categories
    const categoryMap: Record<string, string> = {};

    for (const cat of categories) {
      const created = await prisma.category.upsert({
        where: { slug: cat.slug },
        update: { name: cat.name, icon: cat.icon },
        create: { name: cat.name, slug: cat.slug, icon: cat.icon },
      });
      categoryMap[cat.slug] = created.id;
      categoryCount++;
    }

    // Create products
    for (const product of products) {
      const categoryId = categoryMap[product.categorySlug];
      if (!categoryId) continue;

      const { categorySlug, ...productData } = product;

      const existingBySlug = await prisma.product.findUnique({ where: { slug: product.slug } });
      const existingBySku = await prisma.product.findUnique({ where: { sku: product.sku } });
      if (existingBySlug) {
        await prisma.product.update({ where: { slug: product.slug }, data: { ...productData, categoryId } });
      } else if (existingBySku) {
        await prisma.product.update({ where: { sku: product.sku }, data: { ...productData, categoryId } });
      } else {
        await prisma.product.create({ data: { ...productData, categoryId } });
      }

      productCount++;
    }

    // Create sample orders for demo (phone: 9876543210)
    const sampleProducts = await prisma.product.findMany({ take: 6 });

    const sampleOrders = [
      {
        orderNumber: "IN-20260410-1001",
        customerName: "Rajesh Kumar",
        customerPhone: "9876543210",
        company: "Kumar Engineering Works",
        address: "Plot 42, Sector 18, Noida, UP 201301",
        status: "delivered",
        paymentStatus: "paid",
        subtotal: 2610,
        gst: 470,
        total: 3080,
        items: sampleProducts.slice(0, 2).map((p, i) => ({
          productId: p.id,
          quantity: i === 0 ? 3 : 1,
          price: p.sellingPrice,
        })),
      },
      {
        orderNumber: "IN-20260410-1002",
        customerName: "Rajesh Kumar",
        customerPhone: "9876543210",
        company: "Kumar Engineering Works",
        address: "Plot 42, Sector 18, Noida, UP 201301",
        status: "out_for_delivery",
        paymentStatus: "paid",
        subtotal: 4280,
        gst: 770,
        total: 5050,
        items: sampleProducts.slice(2, 4).map((p) => ({
          productId: p.id,
          quantity: 2,
          price: p.sellingPrice,
        })),
      },
      {
        orderNumber: "IN-20260410-1003",
        customerName: "Rajesh Kumar",
        customerPhone: "9876543210",
        company: "Kumar Engineering Works",
        address: "Plot 42, Sector 18, Noida, UP 201301",
        status: "confirmed",
        paymentStatus: "pending",
        subtotal: 1480,
        gst: 266,
        total: 1746,
        items: sampleProducts.slice(4, 6).map((p) => ({
          productId: p.id,
          quantity: 1,
          price: p.sellingPrice,
        })),
      },
    ];

    let orderCount = 0;
    for (const order of sampleOrders) {
      const existing = await prisma.order.findUnique({
        where: { orderNumber: order.orderNumber },
      });
      if (!existing && order.items.length > 0) {
        const { items, ...orderData } = order;
        await prisma.order.create({
          data: {
            ...orderData,
            items: { create: items },
          },
        });
        orderCount++;
      }
    }

    return NextResponse.json({
      message: "Seeded successfully",
      categories: categoryCount,
      products: productCount,
      orders: orderCount,
    });
  } catch (error) {
    console.error("POST /api/seed error:", error);
    return NextResponse.json({ error: "Seed failed", details: String(error) }, { status: 500 });
  }
}
